<?php

/**
 * Implements HOOK_menu()
 */
function exporter_dashboard_menu() {

    $items['exporter-dashboard/splashviews'] = array(
        'title' => 'Export.gov Portal',
        'page callback' => 'theme',
        'page arguments' => array('exporter_dashboard_splashviews', array()),
        'access arguments' => array(true),
        'access callback' => true,
        'type' => MENU_CALLBACK,
    );
  
  return $items;
}

function exporter_dashboard_theme() {
    $themes = array();
    $themes['exporter_dashboard_splash'] = array(
        'template' => 'exporter_dashboard_splash',
        'variables' => array(),
    );
    $themes['exporter_dashboard_choose_subcategory'] = array(
        'template' => 'exporter_dashboard_choose_subcategory',
        'variables' => array(),
    );
    $themes['exporter_dashboard_results'] = array(
        'template' => 'exporter_dashboard_results',
        'variables' => array(),
    );
    $themes['exporter_dashboard_splashviews'] = array(
        'template' => 'exporter_dashboard_splashviews',
        'variables' => array(),
    );
    return $themes;
}

/**
 * Implementation of hook_preprocess_HOOK().
 */
function exporter_dashboard_preprocess_exporter_dashboard_splash(&$variables) {
    
    $variables['countries'] = array();
    $results = db_query("
        SELECT DISTINCT field_appoffice_country_value 
        FROM field_data_field_appoffice_country c
        LEFT JOIN field_data_field_appoffice_type t ON  ( c.entity_id = t.entity_id )
        WHERE
            field_appoffice_type_value  = 'U.S. Export Assistance Center'
            AND field_appoffice_country_value <> 'us'
        ORDER BY field_appoffice_country_value
    ");
    foreach ( $results as $record ) {
        $countryName = $record->field_appoffice_country_value;
        $countryCode = countryNameToAcronym($countryName);
        if ( $countryCode !== false ) {
            $variables['countries'][ $countryCode ] = $countryName;
        }
    }
}

/**
 * Implementation of hook_preprocess_HOOK().
 */
function exporter_dashboard_preprocess_exporter_dashboard_results(&$variables) {
    
    $category = trim( strtolower($variables['category']) );
    $subcategory = trim( strtolower($variables['subcategory']) );
    
    $variables['sectionClassFriendlyName'] = strtolower( str_replace(' ', '', $category) );
    
    switch ( strtolower(trim($category)) ) {
        case 'learn':
            $sectionMessage = "Learn more about exporting. Find out how exporting could benefit your business. Get information about the steps you need to take to begin exporting.";
            $subSectionOptions = array(
                array(
                    'title' => 'Basic Information',
                    'div' => 'learn-information',
                    'imagesrc' => '/sites/all/themes/bususa/images/exporterdashboard/learn-information.png',
                    'link' => '/exporter-dashboard/results?category=Learn&subcategory=Information'
                ),
                array(
                    'title' => 'Research Tools',
                    'div' => 'learn-research',
                    'imagesrc' => '/sites/all/themes/bususa/images/exporterdashboard/learn-research.png',
                    'link' => '/exporter-dashboard/results?category=Learn&subcategory=Research'
                ),
                array(
                    'title' => 'Consulting Support',
                    'div' => 'learn-consulting',
                    'imagesrc' => '/sites/all/themes/bususa/images/exporterdashboard/learn-consulting.png',
                    'link' => '/exporter-dashboard/results?category=Learn&subcategory=Consulting'
                )
            );
            break;
        case 'comply':
            $sectionMessage = "Exports require compliance before you can ship your product(s). Foreign countries have different standards for importing. Use the information here to comply with the licenses, standards and legal considerations that may apply to your product(s).";
            $subSectionOptions = array(
                array(
                    'title' => 'Documentation',
                    'div' => 'comply-document',
                    'imagesrc' => '/sites/all/themes/bususa/images/exporterdashboard/comply-document.png',
                    'link' => '/exporter-dashboard/results?category=Comply&subcategory=Document'
                ),
                array(
                    'title' => 'Certification',
                    'div' => 'comply-certify',
                    'imagesrc' => '/sites/all/themes/bususa/images/exporterdashboard/comply-certify.png',
                    'link' => '/exporter-dashboard/results?category=Comply&subcategory=Certify'
                ),
                array(
                    'title' => 'Shipping',
                    'div' => 'comply-ship',
                    'imagesrc' => '/sites/all/themes/bususa/images/exporterdashboard/comply-ship.png',
                    'link' => '/exporter-dashboard/results?category=Comply&subcategory=Ship'
                ),

            );
            break;
        case 'assistance and opportunities':
            $sectionMessage = "Discover exporting opportunities from the State Department and other government agencies to benefit your business. Learn about resources available to your business across the world whenever your business encounters issues.";
            $subSectionOptions = array(
                array(
                    'title' => 'For Basic Assistance',
                    'div' => 'assistanceandopportunities-contacts',
                    'imagesrc' => '/sites/all/themes/bususa/images/exporterdashboard/assistance-contacts.png',
                    'link' => '/exporter-dashboard/results?category=Assistance%20and%20Opportunities&subcategory=Contacts'
                ),
                array(
                    'title' => 'For Financing',
                    'div' => 'assistanceandopportunities-exportfinance',
                    'imagesrc' => '/sites/all/themes/bususa/images/exporterdashboard/assistance-finance.png',
                    'link' => '/exporter-dashboard/results?category=Assistance%20and%20Opportunities&subcategory=Export%20Finance'
                ),
                array(
                    'title' => 'For Trade Problems',
                    'div' => 'assistanceandopportunities-tradeproblems',
                    'imagesrc' => '/sites/all/themes/bususa/images/exporterdashboard/assistance-trade.png',
                    'link' => '/exporter-dashboard/results?category=Assistance%20and%20Opportunities&subcategory=Trade%20Problems'
                )
            );
            break;
        case 'teach tell me about exporting':
            //$sectionMessage = "Discover exporting opportunities from the State Department and other government agencies to benefit your business. Learn about resources available to your business across the world whenever your business encounters issues.";
            $subSectionOptions = array(

            );
            break;
        default:
            $msg = '<!-- /* Coder Bookmark: CB-KMZJ2FY-BC */ -->';
            $msg .= 'Invalid value for the <i>category</i> parameter: ' . $category;
            $msg .= '<!-- switch is: ' . strtolower(trim($category)) . ' -->';
            drupal_set_message($msg, 'error');
            return; // Cease rendering this script
    }
    
    $variables['sectionMessage'] = $sectionMessage;
    $variables['subSectionOptions'] = $subSectionOptions;
    $variables['exportDashboardSectionsAndLinks'] = exporter_dashboard_getResultPageLinks($category, $subcategory); // Note: getExportDashboardLandingPageLinks() is defined in ConsumeData-Export.govSiteRip.php
    
}

/**
 * Implementation of hook_preprocess_HOOK().
 */
function exporter_dashboard_preprocess_exporter_dashboard_choose_subcategory(&$variables) {

    
    $variables['sectionClassFriendlyName'] = strtolower( str_replace(' ', '', $variables['chosenSection']) );
    
    switch ($variables['chosenSection']) {
        case 'Learn':
            $sectionMessage = "Learn more about exporting. Find out how exporting could benefit your business. Get information about the steps you need to take to begin exporting.";
            $subSectionOptions = array(
                array(
                    'title' => 'Basic Information',
                    'imagesrc' => '/sites/all/themes/bususa/images/exporterdashboard/learn-information.png',
                    'link' => '/exporter-dashboard/results?category=Learn&subcategory=Information',
                    'div' => 'learn-information',
                ),
                array(
                    'title' => 'Research Tools',
                    'imagesrc' => '/sites/all/themes/bususa/images/exporterdashboard/learn-research.png',
                    'link' => '/exporter-dashboard/results?category=Learn&subcategory=Research',
                    'div' => 'learn-research',
                ),
                array(
                    'title' => 'Consulting Support',
                    'imagesrc' => '/sites/all/themes/bususa/images/exporterdashboard/learn-consulting.png',
                    'link' => '/exporter-dashboard/results?category=Learn&subcategory=Consulting',
                    'div' => 'learn-consulting'
                )
            );
            break;
        case 'Comply':
            $sectionMessage = "Exports require compliance before you can ship your product(s). Foreign countries have different standards for importing. Use the information here to comply with the licenses, standards and legal considerations that may apply to your product(s).";
            $subSectionOptions = array(
                array(
                    'title' => 'Documentation',
                    'imagesrc' => '/sites/all/themes/bususa/images/exporterdashboard/comply-document.png',
                    'link' => '/exporter-dashboard/results?category=Comply&subcategory=Document',
                    'div' => 'comply-document'
                ),
                array(
                    'title' => 'Certification',
                    'imagesrc' => '/sites/all/themes/bususa/images/exporterdashboard/comply-certify.png',
                    'link' => '/exporter-dashboard/results?category=Comply&subcategory=Certify',
                    'div' => 'comply-certify'
                ),
                array(
                    'title' => 'Shipping',
                    'imagesrc' => '/sites/all/themes/bususa/images/exporterdashboard/comply-ship.png',
                    'link' => '/exporter-dashboard/results?category=Comply&subcategory=Ship',
                    'div' => 'comply-ship'
                ),

            );
            break;
        case 'Assistance and Opportunities':
            $sectionMessage = "Discover exporting opportunities from the State Department and other government agencies to benefit your business. Learn about resources available to your business across the world whenever your business encounters issues.";
            $subSectionOptions = array(
                array(
                    'title' => 'For Basic Assistance',
                    'imagesrc' => '/sites/all/themes/bususa/images/exporterdashboard/assistance-contacts.png',
                    'link' => '/exporter-dashboard/results?category=Assistance%20and%20Opportunities&subcategory=Contacts',
                    'div' => 'assistanceandopportunities-contacts'
                ),
                array(
                    'title' => 'For Financing',
                    'imagesrc' => '/sites/all/themes/bususa/images/exporterdashboard/assistance-finance.png',
                    'link' => '/exporter-dashboard/results?category=Assistance%20and%20Opportunities&subcategory=Export%20Finance',
                    'div' => 'assistanceandopportunities-exportfinance'
                ),
                array(
                    'title' => 'For Trade Problems',
                    'imagesrc' => '/sites/all/themes/bususa/images/exporterdashboard/assistance-trade.png',
                    'link' => '/exporter-dashboard/results?category=Assistance%20and%20Opportunities&subcategory=Trade%20Problems',
                    'div' => 'assistanceandopportunities-tradeproblems'
                )
            );
            break;
        default:
            print 'Invalid value for the <i>category</i> parameter.';
            return; // Cease rendering this script
    }
    
    $variables['sectionMessage'] = $sectionMessage;
    $variables['subSectionOptions'] = $subSectionOptions;

}

function exporter_dashboard_getResultPageLinks($category, $subcategory) {
    
    $ret = array();
    
    $category = getEasyCompareString($category); // Strip spaces, dashes, underscores, and make lower-casse
    $subcategory = getEasyCompareString($subcategory); // Strip spaces, dashes, underscores, and make lower-casse
    
    // Load all mapps from an Excel spreadsheet - load this information into an array
    $mappingFilePath = variable_get('exporter_dashboard_mappings_filepath', drupal_get_path('module', 'exporter_dashboard') . '/export-dashboard-mappings.xls' );
    $mappings = exporter_dashboard_excelToArray( $mappingFilePath ); // Note: excelToArray() is defined in below

    // Foreach row in this spreadhseet...
    foreach ( $mappings as $mapping ) {
        
        $thisRowCategory = getEasyCompareString( $mapping['assoc']['section'] ); // Strip spaces, dashes, underscores, and make lower-casse
        $thisRowSubCategory = getEasyCompareString( $mapping['assoc']['subsection'] ); // Strip spaces, dashes, underscores, and make lower-casse
        $thisRowAltCategory = getEasyCompareString( $mapping['assoc']['altsection'] ); // Strip spaces, dashes, underscores, and make lower-casse
        
        // Check if this row describes a page that should be shown in this section & sub-section of the Export-Dashboard
        if ( 
            ( $category == $thisRowCategory || $category == $thisRowAltCategory ) 
            && ( $subcategory == $thisRowSubCategory || $subcategory == $thisRowAltCategory ) 
        ) {
        
            // Ensure there is an array in the root of $ret for this dashboard_cateory_title
            $dashboardCateorTitle = $mapping['assoc']['dashboard_cateory_title'];
            if ( !isset($ret[$dashboardCateorTitle]) ) {
                $ret[$dashboardCateorTitle] = array();
            }
            
            // Validation and checking
            $warning = false;
            
            // Validation and checking - Make sure there was a title given
            $linkTitle = $mapping['assoc']['dashboard_link_title'];
            if ( trim(strval($mapping['assoc']['topic_post'])) !== '' ) {
                $linkTitle = $mapping['assoc']['topic_post'];
            }
            if ( strval($linkTitle) === '' ) {
                $linkTitle = false;
                $warning = true;
            }
            
            // Determin the link URL
            $linkUrl = $mapping['assoc']['dashboard_link_url'];
            if ( strpos($linkUrl, 'export.gov') !== false ) { // This if-block will not pass external-links outside of export.gov, and not passt links with mailto: in them
            
                if ( strval($mapping['assoc']['dashboard_cateory_title']) !== '' && strval($mapping['assoc']['dashboard_link_title']) !== '' ) {
                    $catTitle = $mapping['assoc']['dashboard_cateory_title'];
                    $catTitle = getEasyCompareString($catTitle, null, true, true, true, '-'); // Replace all dashes, slashes, Unicode, punctuations, etc, with dashes
                    $linkUrl = '/export/' . $catTitle . '/' . getEasyCompareString($linkTitle, null, true, true, true, '-');
                    if ( !empty($mapping['assoc']['retain_ref_cats']) && intval($mapping['assoc']['retain_ref_cats']) === 1 ) { // Since the system will look in the spreadsheet based on the url where http://business.usa.gov/export/ColumnA/ColumnB, and there are duplicated across column A&B on the spread sheet, retain the refering category and subcategory for breadcrumb sake on the target page
                        $linkUrl .= "?cat={$category}&subcat={$subcategory}";
                    }
                }
                if ( strval($mapping['assoc']['dashboard_cateory_title']) !== '' && strval($mapping['assoc']['topic_post']) !== '' ) {
                    $catTitle = $mapping['assoc']['dashboard_cateory_title'];
                    $catTitle = getEasyCompareString($catTitle, null, true, true, true, '-'); // Replace all dashes, slashes, Unicode, punctuations, etc, with dashes
                    $topicPost = $mapping['assoc']['topic_post'];
                    $topicPost = getEasyCompareString($topicPost, null, true, true, true, '-'); // Replace all dashes, slashes, Unicode, punctuations, etc, with dashes
                    $linkUrl = '/export/' . $catTitle . '/' . $topicPost;
                    if ( !empty($mapping['assoc']['retain_ref_cats']) && intval($mapping['assoc']['retain_ref_cats']) === 1 ) { // Since the system will look in the spreadsheet based on the url where http://business.usa.gov/export/ColumnA/ColumnB, and there are duplicated across column A&B on the spread sheet, retain the refering category and subcategory for breadcrumb sake on the target page
                        $linkUrl .= "?cat={$category}&subcat={$subcategory}";
                    }
                }
            }
            
            // Validation and checking - Make sure there was a link given
            if ( strval($linkUrl) === '' ) {
                $linkUrl = "javascript: alert('No URL given in spreadhseet');";
                $warning = true;
            }
            
            
            // We will want to return pages information under the (dashboard_cateory_title) array
            if ( $linkTitle !== false ) {
                $ret[$dashboardCateorTitle][] = array(
                    'url' => $linkUrl,
                    'title' => $linkTitle,
                    'warning' => $warning
                );
            }
            
        }
        
    }
    
    return $ret;
}

/** array exporter_dashboard_excelToArray(string $spreadsheetPath, int $workSheetNumber = 0, int $rowwOffset = 0)
  *
  *  Given a path to an Excel file, will read the file and return the contents within it, pased as an array.
  */
function exporter_dashboard_excelToArray($spreadsheetPath, $workSheetNumber = 0, $rowwOffset = 0) {

    // Include the PHPExcel library
    exporter_dashboard_includePhpExcel();
    
    // load the spreadsheet
    $objPHPExcel = PHPExcel_IOFactory::load($spreadsheetPath);
    
    $excelHeaders = array();
    $excelArray = array();
    
    $currentWkSheetNumb = -1;
    foreach ($objPHPExcel->getWorksheetIterator() as $worksheet) {
    
        $currentWkSheetNumb++;
    
        if ( $workSheetNumber === $currentWkSheetNumb ) {
        
            $highestRow = $worksheet->getHighestRow(); // e.g. 10
            $highestColumn = $worksheet->getHighestColumn(); // e.g 'F'
            $highestColumnIndex = PHPExcel_Cell::columnIndexFromString($highestColumn);
            $nrColumns = ord($highestColumn) - 64;

            // Get the headers - assume the cells on the first row are headers
            for ($col = 0; $col < $highestColumnIndex; ++ $col) {
                $excelHeaders[$col] = $worksheet->getCellByColumnAndRow($col, 1 + $rowwOffset)->getValue();
            }
            
            for ($row = 2 + $rowwOffset; $row <= $highestRow; ++ $row) {
                $excelArray['row-' . $row] = array(
                    'assoc' => array(),
                    'cols' => array()
                );
                for ($col = 0; $col < $highestColumnIndex; ++ $col) {
                    $thisColHeader = $excelHeaders[$col];
                    $thisCellValue = $worksheet->getCellByColumnAndRow($col, $row)->getValue();
                    $excelArray['row-' . $row]['assoc'][$thisColHeader] = $thisCellValue;
                    $excelArray['row-' . $row]['cols'][$col] = $thisCellValue;
                }
            }
        
        }
    }
    
    // Array cleanup - Check the last rows of the array, if all of the cells (coumns) for this row are null, remove the row
    $rowsInArray_ReverseOrder = array_reverse( array_keys($excelArray) );
    foreach ( $rowsInArray_ReverseOrder as $rowKey ) {
        if ( strval(@implode('', $excelArray[$rowKey]['cols'])) === '' ) { // If there is no information (if all the elements in this array are null)...
            unset( $excelArray[$rowKey] ); // Remove this row from the array
        } else {
            break; // Do not check any more rows in the array
        }
    }
    
    return $excelArray;
}

/** bool exporter_dashboard_includePhpExcel()
  *
  *  Searches for and inclues the PHPExcel library
  *  Returns TRUE only when the PHPExcel library is found and includes, FALSE otherwise.
  */
function exporter_dashboard_includePhpExcel() {

    if ( is_dir('sites/all/libraries/PHPExcel') && strpos(get_include_path(), 'sites/all/libraries/PHPExcel') === false ) {
        set_include_path( get_include_path() . PATH_SEPARATOR . 'sites/all/libraries/PHPExcel/' );
    }
    
    if ( !@include_once('PHPExcel.php') ) {
        return false;
    } else {
        return true;
    }

}
